---
title: "Tidy Tuesdays - Hotel Bookings"
author: "Nellie Ponarul"
date: "2/11/2020"
output: html_document
---

```{r setup, include=FALSE, results = "hide"}
knitr::opts_chunk$set(echo = TRUE)
source("000_init.R")
```

### Introduction
This dataset from [Antonio, Almeida and Nunes, 2019](https://www.sciencedirect.com/science/article/pii/S2352340918315191#bib3) has resort and city hotel bookings between July 2015 and August 2017. 

### Exploration

# Distribution of the Number of Booking Changes: Resort vs. City Hotel

```{r, echo = FALSE, results = "hide"}
summary(hotels$stays_in_weekend_nights)
summary(hotels$stays_in_week_nights)

(p1 <- ggplot(hotels %>% filter(booking_changes <=10 & booking_changes >= 1), aes(x = booking_changes, fill = hotel))+
   geom_histogram(position = "dodge", binwidth = .52)+
    scale_y_continuous(labels = scales::comma)+
    scale_fill_manual(values = RColorBrewer::brewer.pal(4, "Set1"), name = "Type of Hotel")+ # selected from RColorBrewer::brewer_pal("Blues")
    labs(x = "Number of Booking Changes", y = "Number of Bookings")+
    theme_bw()+
    ggtitle("Distribution of Booking Changes: City Hotel vs. Resort Hotel", subtitle = "Limited to bookings with at least one change and less than 10 changes"))

```

# Distribution of Lead Time For Canceled and Not-Canceled reservations


```{r, echo = FALSE}

(p2 <- ggplot(hotels %>% mutate(is_canceled = ifelse(is_canceled == 1, "Canceled", "Not Canceled")) %>% filter(hotel == "Resort Hotel"), aes(x = lead_time, fill = is_canceled))+
   geom_histogram(position = "dodge", binwidth = 30)+
    scale_x_continuous(breaks = seq(0,500, 50))+
    scale_y_continuous(breaks = seq(0,10000,500),labels = scales::comma)+
    scale_fill_manual(values = RColorBrewer::brewer.pal(4, "Set1"), name = "Type of Hotel")+ 
    labs(x = "Number of Days Ahead the Booking Was Made", y = "Number of Bookings")+
    theme_bw()+
    ggtitle("Distribution of Lead Time for Canceled and Not-Canceled reservations", subtitle = "Resort Hotels Only"))

```

```{r, echo = FALSE}
(p3 <- ggplot(hotels %>% mutate(is_canceled = ifelse(is_canceled == 1, "Canceled", "Not Canceled")) %>% filter(hotel == "City Hotel"), aes(x = lead_time, fill = is_canceled))+
   geom_histogram(position = "dodge", binwidth = 30)+
    scale_x_continuous(breaks = seq(0,700, 50))+
    scale_y_continuous(labels = scales::comma)+
    scale_fill_manual(values = RColorBrewer::brewer.pal(4, "Set1"), name = "Type of Hotel")+ 
    labs(x = "Number of Days Ahead the Booking Was Made", y = "Number of Bookings")+
    theme_bw()+
    ggtitle("Distribution of Lead Time for Canceled and Not-Canceled reservations", subtitle = "City Hotels Only"))
```

